### ISSUE TITLE
AWS Lambda deployment only allows for selection of nodejs 12

### ISSUE THREAD

**Issue by ScottDellinger** [aws/aws-toolkit-visual-studio#303] opened 2022-11-23 19:34 UTC
**Describe the bug**
The AWS Lambda deployment only allows for selection of nodejs 12 Lambda runtime. This has been deprecated by AWS and 16 is now the standard. We currently have to deploy as nodejs 12 then go into AWS console to update to nodejs 16.

**To Reproduce**
Open/create Lambda project. Right-click on project in Solution explorer, select Publish to AWS Lambda.

**Expected behavior**
nodejs v 16 should be showing in the dropdown for Lambda runtime.

**Screenshots**
![image](https://user-images.githubusercontent.com/16200100/203631254-8030d91a-d90e-40a4-9043-f2c10aa6088e.png)

**Computer (please complete the following information):**

- Windows Version: 11
- Visual Studio Version: 17.4.1
- AWS Toolkit for Visual Studio Version: Not sure how to check this, but I just updated it to the one available in the Visual Studio notifications (most recent)

**Additional context**
N/A

**Comment by awschristou** [comment] 2022-11-24 00:24
Closing as a duplicate of #286 

@ScottDellinger , please take a moment to add a reaction to that issue to help us measure interest, and mention your Visual node development in Visual Studio story. We would like to understand how much node development is taking place within Visual Studio.

**Closed by awschristou** 2022-11-24 00:24 UTC
Labels: bug, duplicate

**Comment by martinhowell** [comment] 2023-04-14 16:52
I have this problem also.

It seems very odd that only node v12 is supported to deploy lambda projects when this is deprecated and in fact I cant use the lastest v3 aws-sdk becaUSE IT WONT WORK so I cant use some of the latest AWS features like eventbridge scheduler.

And dont get me started on the use of modules vs commonjs what a mess!!
