### ISSUE TITLE
Support for Amazon Q in Visual Studio

### ISSUE THREAD

**Issue by akshatparikh** [aws/aws-toolkit-visual-studio#418] opened 2024-04-23 17:51 UTC
**Is your feature request related to a problem? Please describe.**
This is a generic feature request, not related to a problem

**Describe the solution you'd like**
It would be great if developers can get support of Amazon Q through AWS Toolkit for Visual Studio 

**Describe alternatives you've considered**
N/A

**Comment by awschristou** [comment] 2024-04-23 20:12
Thanks for reaching out @akshatparikh  . This is a duplicate of the request in #392 , and will be closed. Please add a +1 reaction to that issue to register your interest in this feature.

![image](https://github.com/aws/aws-toolkit-visual-studio/assets/39839589/7812353e-6f05-4247-9cfe-6c0db51a937f)

**Closed by awschristou** 2024-04-23 20:12 UTC
Labels: feature-request
