### ISSUE TITLE
AWS SSO Prompts Are Extremely Intrusive And Disruptive

### ISSUE THREAD

**Issue by MadQ** [aws/aws-toolkit-visual-studio#222] opened 2022-03-03 19:26 UTC
This is feedback, not a question.

The AWS SSO login process very laborious and slow. It opens a URL in a web browser that redirects numerous times, and then requires no less than five user interactions across three form submissions, each of which is unbearably slow. This would be fine if it only needed to be done once (a.k.a a Single time). The fact that re-authentication is required every 12 hours means that SSO is a misnomer.

The AWS Toolkit extension for Visual Studio automatically opens the following modal message box prompting the user to sign on using AWS SSO:
![image](https://user-images.githubusercontent.com/4042105/156606146-ca6220c1-a1fd-4fdc-98be-1bfb3cec8a9a.png)

This message box is extremely intrusive and disruptive, as it is impossible for the user to continue whatever they were doing until they either sign on to AWS SSO, or dismiss the message box. However, when either clicking _Cancel_ or hitting the Esc key, another message box is shown:
![image](https://user-images.githubusercontent.com/4042105/156615701-7576ae66-8072-45b9-bf13-7651a8455de5.png)

After clicking _OK_, the above sign on process repeats a number of times (sometimes 20 times or more).

**Comment by awschristou** [comment] 2022-03-03 19:49
Hi @MadQ thanks for sharing about your experience. I can understand your frustrations around modal dialogs and clicking through the login flow. Let's make sure I understand your working environment.

The SSO Login dialog isn't intended to be displayed until there is an operation that explicitly requires an AWS connection. For example, the AWS Explorer for example should go into a state where it requires you to explicitly start the connection process. This way, you do not get prompted to make an SSO connection whenever you start the IDE. If that isn't your experience, that would be great to know, so that we can investigate it further.

That's the baseline functionality. Based on your second dialog, it looks like you've associated an SSO based profile to your CodeArtifact credential provider. I'm assuming you've set up your system using CodeArtifact as a NuGet package source. When you restore your project's referenced packages, this requires AWS credentials to communicate with CodeArtifact. I believe Visual Studio's default configuration is to automatically restore NuGet packages when you load a solution (this behavior can be adjusted). Does this align with when and why you are seeing the login prompts?

The session duration for an SSO Token can be configured between 1-12 hours from the AWS SSO console ([documentation](https://docs.aws.amazon.com/singlesignon/latest/userguide/howtosessionduration.html)).

**Comment by MadQ** [comment] 2022-03-03 21:47
Thanks for your response, @awschristou . You are correct regarding the CodeArtifact NuGet source. When the CodeArtifacts NuGet source is enabled, Visual Studio (2022) will prompt for AWS SSO every time a build is initiated, but also more or less randomly, which I am guessing is due background code analysis. Disabling automatic package restore is not really an option, as it is a feature I rely on heavily.

Temporarily disabling the CodeArtifacts NuGet source avoids the issue, but it's a cumbersome workaround.

I think the best solution to my issue would be for the AWS ToolKit extension **not** to retry SSO signons after the user clicks _Cancel_, and instead to provide a warning/infobar below the VS toolbars (similar to the ones VS provides for issues with extension, failed code analyzers, etc), with the option to manually retry the SSO signon. I.e. the concept of "Stop bothering me until I say otherwise". If the repo for the extension were public, I might even volunteer to implement that.

Incidentally (and unrelated), the AWS ToolKit Output Window pane automatically comes to the foreground when something is written to that pane. It would be nice to have an option to disable that, so that the focus is not stolen from whichever pane is currently active.

**Comment by awschristou** [comment] 2022-03-03 22:49
Thanks for the insight, we'll have to look further into how the extension provides NuGet credentials into Visual Studio, to see if we can defer connections without fully disabling that connection for the duration of your IDE session. To help me understand your situation, when you cancel the SSO login, do your builds (or analyzers and anything else that triggers NuGet) succeed? I'm assuming packages are then consumed from the local cache but would like to confirm.

About the Output window -- we had some noisy credentials related messages that were taking focus, which we stopped taking focus for in v1.25.0.0 and newer of the Toolkit. There are some messages that I think we'd want you to see when they are directly related to some action you've taken in the Toolkit, but its likely there are some other ones that should be made more silent. Do you have some examples of messages that are stealing focus that should be considered more passive?

**Comment by MadQ** [comment] 2022-03-04 14:48
Yes, that is correct. After the SSO login is cancelled, everything completes successfully.

The highlighted messages in the following screenshot seem purely informational and could be considered more passive:
![image](https://user-images.githubusercontent.com/4042105/156783784-4731bfc1-9f36-4379-b80c-2b8f495ec91d.png)

**Comment by awschristou** [comment] 2022-03-04 18:52
Your use case around CodeArtifact has provided some great context around these messages. We'd already updated the "Reloaded..." and "Profiles found..." messages to no longer steal focus, but the Start/Error cases around SSO and MFA logins were still set to require focus. This turns out to be aggressive when something like CodeArtifact connections tries repeatedly to auth.

I've updated these messages so that they won't take focus. This change should make its way out in a future Toolkit release.

**Comment by patrickvecchio** [comment] 2022-03-26 00:37
Adding some context of my own.  This behavior changed not long ago.  You used to be able to dismiss the dialog about 5 times before it would give up.  Now it seems to go on forever.  I have a plain, vanilla install of the AWS toolkit (pretty much just use it for the AWS Explorer).  Also, as MadQ stated, my observation is that it's fairly random.  When it happens I can login (which is tedious - click the link, log in to SSO, grab my MFA device, complete the login, click "Allow", go to the numerous instances of Visual Studio I have open an close those dialogs so I don't have to repeat 8-ish times) or if I'm unable to login for some reason (which has happened), the only solution I've found is to kill the devenv.exe process.

Expected behavior:  Make the "Cancel" button respect my wishes and cancel.

- Windows Version: 11
- Visual Studio Version: 2022
- AWS Toolkit for Visual Studio Version: 1.26.0.0

**Comment by awschristou** [comment] 2022-07-26 14:06
Version 1.35.1.0 was recently released. It contains a fix that will prevent the CodeArtifact connections from prompting for an SSO login as much as it was after you cancel. It should also prevent the IDE from attempting to fall back to a more generic system login dialog as well.

We haven't introduced a way to "pause and resume" making CodeArtifact connections, so you will likely continue to receive prompts the next time the IDE needs to access the CodeArtifact feed (for example, when you manage NuGet packages, or recompile).

I will close this issue. If the new version is still disruptive, please open a new issue for further discussion.

**Closed by awschristou** 2022-07-26 14:06 UTC
