### ISSUE TITLE
Publish to AWS Lambda is not honoring the aws-lambda-tools-defaults.json file

### ISSUE THREAD

**Issue by genifycom** [aws/aws-toolkit-visual-studio#154] opened 2021-04-29 16:45 UTC
**Describe the bug**
Publish to AWS Lambda is not honoring the aws-lambda-tools-defaults.json file.

**To Reproduce**
In my aws-lambda-tools-defaults.json file I have the following region set.

    "region"      : "us-west-1",

However, when I try to Publish to AWS Lambda I get the following

aws Publish AWS Serverless Application
AWS Credentials Profile:myprofile Region: Africa (Cape Town)
Followed by "Unable to connect to AWS: The security token included in the request is invalid"

**Expected behavior**
The Publish to AWS Lambda would use the indicated region.

**Screenshots**

**Computer (please complete the following information):**

- Windows Version: 10 Version 20H2
- Visual Studio Version: 16.9.4
- AWS Toolkit for Visual Studio Version: 1.21.1.0

**Additional context**

**Comment by awschristou** [comment] 2021-04-29 17:53
Thank you for reporting this issue @genifycom - I've confirmed that publishing either Lambda functions or serverless projects appears to open the dialog and select the region used in the AWS Explorer. We should look into selecting the region specified in the json file first.

**Comment by awschristou** [comment] 2022-03-23 22:17
Closing as duplicate of #224

**Closed by awschristou** 2022-03-23 22:17 UTC
Labels: bug
