### ISSUE TITLE
Open SSH Session Error

### ISSUE THREAD

**Issue by IvanFarkas** [aws/aws-toolkit-visual-studio#160] opened 2021-06-14 14:51 UTC
**Open SSH Session Error**
- Error 1: _error opening ssh session: The process Cannot access the file 'C:\Users\[user]\AppData\Temp]tmp99F1B.tmp' because it is being used by another process._
- Error 2: _error opening ssh session: Unknown error converting pem to ppk file. Exit Code: -1073741819_

**To Reproduce**
- Create a Serverless ASP.NET Core 5 (Web API in container)
- Publish
- AWS Explorer -> AWS Elastic Beanstalk -> [Application] (Serverless) -> [Environment] (Serverless-dev)
- Click Connect to Instance
- Enter Private Key
- Click OK
- Get Error 1: _error opening ssh session: The process Cannot access the file 'C:\Users\[user]\AppData\Temp]tmp99F1B.tmp' because it is being used by another process._
- Close Error.
- Click OK again.
- Get Error 2: _error opening ssh session: Unknown error converting pem to ppk file. Exit Code: -1073741819_

**Expected behavior**
SSH session like the one in the SSH_CLI image.

**Screenshots**
**Project Type**
![Prj_type](https://user-images.githubusercontent.com/11818001/121911963-2c2f7800-ccfe-11eb-83d0-b8623de1e1ad.png)

**SSH UI**
![SSH_UI](https://user-images.githubusercontent.com/11818001/121912077-4406fc00-ccfe-11eb-9f79-5fedf8a8ce60.png)

**SSH CLI**
![SSH_CLI](https://user-images.githubusercontent.com/11818001/121912133-4f5a2780-ccfe-11eb-8bd3-af64edb90582.png)

**Error 1**
![Error1](https://user-images.githubusercontent.com/11818001/121912193-5f720700-ccfe-11eb-9d9c-9c5c4b95602e.png)

**Error 2**
![Error2](https://user-images.githubusercontent.com/11818001/121912225-6862d880-ccfe-11eb-81d2-298f8a83ff97.png)

**Computer (please complete the following information):**
- Windows Version: Win10Pro (21390.1010)
- Visual Studio Version: VS 2019 Pro (16.11.0)
- AWS Toolkit for Visual Studio Version: 1.21.2.0

**Additional context**

**Comment by shruti0085** [comment] 2021-06-25 01:29
Thanks for reaching out @IvanFarkas . Unfortunately I was unable to reproduce your issue completely.

I was able to reproduce `Error 2 - Unknown error converting pem to ppk file` when I provided an incorrect key-pair(exactly like the one in the image attached in the issue description) when connecting to the instance attached to my Beanstalk environment. 

A couple of questions:
* Can you confirm that in this textbox you are providing the contents of the EC2 Key-Pair that you selected while publishing this application to beanstalk through the toolkit?
* Also can you confirm that your EC2 Key-pair is in the correct format ? EC2 Private key supports RSA and must be in PEM format as indicated [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html#how-to-generate-your-own-key-and-import-it-to-aws). The image linked above is providing a dummy keypair which has a beginning line as `BEGIN OPENSSH PRIVATE KEY` as opposed to `BEGIN RSA PRIVATE KEY`.

Lastly, can you re-try with a new VS instance after closing all previous/existing VS instances?

**Comment by awschristou** [comment] 2023-11-15 01:01
Version 1.44.0.0 of the Toolkit was released today. It contains a fix for a bug that was causing SSH connections from the AWS Toolkit to fail with PEM to PPK conversion issues.

**Closed by awschristou** 2023-11-15 01:01 UTC
Labels: bug, pending-release
