### ISSUE TITLE
Subpar experience in Visual Studio for AWS Q

### ISSUE THREAD

**Issue by massimogentilini** [aws/aws-toolkit-visual-studio#435] opened 2024-06-25 09:52 UTC
**Is your feature request related to a problem? Please describe.**
The usage of AWS Q from Visual Studio is quite poor compared to VS Code. The lack of the chat window or the context menu is quite disappointing and makes the usage not really useful

**Describe the solution you'd like**
A client for Visual Studio that is AT LEAST good as the VSCode one

**Describe alternatives you've considered**
Not using AWS Q

**Additional context**
The end user experience for this tools is a quite fundamental one. If you want AWS Q to succeed you need to invest in the tooling and UX part.

**Comment by shruti0085** [comment] 2024-06-25 18:48
Thanks for reaching out @massimogentilini  . This is a duplicate of the request in https://github.com/aws/aws-toolkit-visual-studio/issues/392 , and will be closed. Please add a +1 reaction to that issue to register your interest in this feature.

**Closed by shruti0085** 2024-06-25 18:48 UTC
Labels: feature-request
