### ISSUE TITLE
IAM user with MFA generates temporary credential 

### ISSUE THREAD

**Issue by powersparks** [aws/aws-toolkit-visual-studio#80] opened 2020-04-14 14:00 UTC
**Describe the bug**
Attempt to create stack, error said temporary credentials not supported.
Reading of stacks works fine.
**To Reproduce**
Create profile, update Using temporary mfa credentials, restart VS. many things seem to work.

**Expected behavior**
AWS cli supports mfa temp credentials, So should AWS toolkit?

**Computer (please complete the following information):**

- Windows Version:
- Visual Studio Version:2019
- AWS Toolkit for Visual Studio Version: 

**Additional context**
Using GOV cloud.

**Comment by awschristou** [comment] 2020-04-17 00:03
Hi @powersparks , the Visual Studio Toolkit does not support MFA at this time. I will close this issue as a duplicate of #46 - please take a moment to add a +1 reaction to that issue.

The toolkit does support GovCloud regions with [other credential types](https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/credentials.html)

**Closed** 2020-04-17 00:04 UTC
Labels: auth, duplicate
