### ISSUE TITLE
Elastic Beanstalk Environments using Windows images not showing in new Publish to AWS experience

### ISSUE THREAD

**Issue by thakkermukund** [aws/aws-toolkit-visual-studio#312] opened 2022-12-27 10:10 UTC
Publish to new target using Beanstalk on windows shows error as "An error occurred in deployment tool. "
![WebApplication1](https://user-images.githubusercontent.com/20154697/209650779-b230300f-a6b8-4a8d-83d2-1d6d3eaefb8d.png)

Using visual studio 2022
AWS SDK 1.38
Target framework - .NET 6.0

**Comment by floralph** [comment] 2022-12-29 21:54
Thank you for bringing this issue to our attention.  Can you provide more detail on how to reproduce this error.  What settings did you use to create the WebApplication1 project?  

The toolkit uses the AWS dotnet deploy tool to perform these actions.  What results do you get when trying to deploy this project using the deploy tool directly?  https://aws.github.io/aws-dotnet-deploy/docs/commands/deploy/

**Comment by saurabhajmera** [comment] 2023-06-08 21:40
Closing this issue since we haven’t heard back from you in a while. You could try these [troubleshooting steps](https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/general-troubleshoot.html) and if you are still encountering this problem please open a new issue with detailed steps to reproduce it.

**Closed by saurabhajmera** 2023-06-08 21:40 UTC
Labels: needs-response, publish
