### ISSUE TITLE
Unable to publish to AWS

### ISSUE THREAD

**Issue by jzhangustc17** [aws/aws-toolkit-visual-studio#344] opened 2023-06-26 18:33 UTC
![image](https://github.com/aws/aws-toolkit-visual-studio/assets/34775689/650f0bf0-c938-4639-abb6-895f5dab711c)

**Comment by floralph** [comment] 2023-06-27 18:36
Hi, thank you for bringing this issue to our attention.  Was this a one time issue or is it reproducible for you?  If it is reproducible:

1. Reproduce the issue.
1. Run `netstat -o` at a command prompt to see if port 10000 on the localhost/127.0.0.1 is already in use.  The `-o` will display the process ID as the last column of output.
1. Run `tasklist /fi "pid eq <process ID>"` replacing <process ID> with the process ID from the last step.  This will show you the process that owns the socket using port 10000.
1. From the Extensions menu in Visual Studio, select AWS Toolkit / View Toolkit Logs to check for any additional error messages and information for this failure.

**Comment by jzhangustc17** [comment] 2023-06-27 18:51
@floralph thanks for your reply. The issue is gone today. Can it be an AWS issue?

**Comment by saurabhajmera** [comment] 2023-07-06 21:20
@jzhangustc17 I will go ahead and close this issue since it seems you were able to resolve it. Based on the details you provided, its hard to determine if this was an AWS issue. Please feel free to create a new github issue if you run into this again.

**Closed by saurabhajmera** 2023-07-06 21:20 UTC
Labels: bug
