### ISSUE TITLE
Error with Publish to AWS - Unable to verify contents of aws.deploy.cli

### ISSUE THREAD

**Issue by oxex-main** [aws/aws-toolkit-visual-studio#188] opened 2021-10-26 09:15 UTC
Hi

I have just enabled the new Deploy feature for AWS Toolkit for VS 2019 and I am now unable to deploy my .NET Core 3.1 to application to Elastic Beanstalk. 

1. How can I revert to the previous tool? I am unable to deploy critical updates to our system.
2. Is there a fix?

Error message: 
There was a problem trying to open the Publish dialog.
AWS Toolkit was unable to verify the contents of the aws.deploy.cli tool. Restart Visual Studio to try again.

I have reinstalled the extension, restarted Visual Studio. There is no awsdeploy.exe file in the locations suggested by this page:
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/deploy_NET_standalone_tool.html

Please help.

- Windows Version: Windows 10
- Visual Studio Version: 16.9.1
- AWS Toolkit for Visual Studio Version: 1.23.0.0

**Comment by Abou226** [comment] 2021-11-13 00:28
I'm having the same issue and i need to upload an important update to the server. But sending this error. How can i fix this plz.

 Unable to open the Publish to AWS dialog: AWS Toolkit was unable to verify the contents of the aws.deploy.cli tool.
Restart Visual Studio to try again.

**Comment by awschristou** [comment] 2021-11-13 00:31
Hi @Abou226 , please follow through https://github.com/aws/aws-toolkit-visual-studio/issues/188#issuecomment-952047088 for instructions on how to revert to the previous experience, and for how to share logs with us for investigation.

**Comment by Abou226** [comment] 2021-11-13 00:58
Thank you @awschristou  So i need to remove this File ?
![2021-11-13](https://user-images.githubusercontent.com/50662604/141599567-9cfc437b-e51a-4847-bbf2-0fba2d67bcf7.png)

**Comment by awschristou** [comment] 2021-11-13 01:03
You can remove that file as a way to access the older publish experience, as a workaround. If you can share your toolkit log, we might be able to determine the root cause.

**Comment by Abou226** [comment] 2021-11-13 01:06
@awschristou Ok i removed it. And it went back to the previous state. Thank you !

**Comment by awschristou** [comment] 2021-11-15 18:41
We're currently seeing that this behavior happens when the user profile path contains a space. We are investigating a fix for this.

Related: #185 (associating with Publish experience known issues)

**Comment by awschristou** [comment] 2022-02-17 22:25
Version 1.25.0.0 of the Toolkit has two changes that address this issue:
- the "Publish to AWS" experience now starts up properly if your profile folder contains a space
- you can now access the newer "Publish to AWS" experience and the more established publishing experiences without having to opt in/out from them

**Closed by awschristou** 2022-02-17 22:25 UTC
Labels: bug, publish
