### ISSUE TITLE
Support for logging in with AWS SSO

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-toolkit-visual-studio#84] opened 2020-04-30 15:19 UTC
**Is your feature request related to a problem? Please describe.**
As a user, I should be able to use AWS SSO to login to the Visual Studio toolkit

**Comment by awschristou** [comment] 2020-06-04 00:59
Closing this issue as a duplicate of #98, since this issue has no engagement, and that one contains a use case.

**Closed by awschristou** 2020-06-04 00:59 UTC
Labels: duplicate, feature-request
