### ISSUE TITLE
Installation Falied Windows Version: 21H2 AWS Toolkit for Visual Studio Version : 17

### ISSUE THREAD

**Issue by Monika1235** [aws/aws-toolkit-visual-studio#330] opened 2023-03-26 09:18 UTC
**Computer (please complete the following information):**

- Windows Version: 21H2
- Visual Studio Version: 17

**Install log**

**Comment by rbbarad** [comment] 2023-03-28 17:25
Hi @Monika1235, could you please attach the installation logs so we can help debug this further?

**Comment by saurabhajmera** [comment] 2023-06-08 21:32
Closing this issue since we haven’t heard back from you in a while. If you are still encountering this problem please open a new issue with detailed steps to reproduce it.

**Closed by saurabhajmera** 2023-06-08 21:32 UTC
Labels: needs-response
