### ISSUE TITLE
VSIXInstaller.NoApplicableSKUsException: This extension cannot be installed on a currently installed product.

### ISSUE THREAD

**Issue by goblinss** [aws/aws-toolkit-visual-studio#301] opened 2022-11-16 05:55 UTC
- Windows Version:
Windows 11 Pro 21H2

- Visual Studio Version:
Visual Studio Enterprise 2022 
(30-day-evaluation-trial)

- AWS Toolkit for Visual Studio Version:
AWSToolkitPackage.v17.vsix

**Install log**
2022/11/16 14:38:57 - Microsoft VSIX Installer
2022/11/16 14:38:57 - -------------------------------------------
2022/11/16 14:38:57 - vsixinstaller.exe version:
2022/11/16 14:38:57 - 17.4.2118-17-4P4Inse-ge4c88902
2022/11/16 14:38:57 - -------------------------------------------
2022/11/16 14:38:57 - Command line parameters:
2022/11/16 14:38:57 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\k\source\repos\AWSToolkitPackage.v17.vsix
2022/11/16 14:38:57 - -------------------------------------------
2022/11/16 14:38:57 - Microsoft VSIX Installer
2022/11/16 14:38:57 - -------------------------------------------
2022/11/16 14:38:57 - Initializing Install...
2022/11/16 14:38:58 - 	Identifier         : 0B82CB16-0E52-4363-9BC0-61E758689176
2022/11/16 14:38:58 - 	Name               : AWS Toolkit for Visual Studio 2022
2022/11/16 14:38:58 - 	Author             : Amazon Web Services
2022/11/16 14:38:58 - 	Version            : 1.37.0.0
2022/11/16 14:38:58 - 	Description        : The AWS Toolkit for Visual Studio is an extension for Microsoft Visual Studio on Windows that makes it easier for developers to develop, debug, and deploy .NET applications using Amazon Web Services.
2022/11/16 14:38:58 - 	Locale             : en-US
2022/11/16 14:38:58 - 	MoreInfoURL        : https://aws.amazon.com/visualstudio/
2022/11/16 14:38:58 - 	InstalledByMSI     : False
2022/11/16 14:38:58 - 	SupportedFrameworkVersionRange : [4.5,)
2022/11/16 14:38:58 - 
2022/11/16 14:39:01 - 	SignatureState     : ValidSignature
2022/11/16 14:39:01 - 	SignedBy           : Amazon.com, Inc.
2022/11/16 14:39:01 - 	Certificate Info   : 
2022/11/16 14:39:01 - 		-------------------------------------------------------
2022/11/16 14:39:01 - 		[Subject]       : CN="Amazon.com, Inc.", O="Amazon.com, Inc.", L=Seattle, S=Washington, C=US
2022/11/16 14:39:01 - 		[Issuer]        : CN=DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1, O="DigiCert, Inc.", C=US
2022/11/16 14:39:01 - 		[Serial Number] : 0E4D3D377B5756257402C169EEED0D47
2022/11/16 14:39:01 - 		[Not Before]    : 2022/09/27 9:00:00
2022/11/16 14:39:01 - 		[Not After]     : 2023/09/28 8:59:59
2022/11/16 14:39:01 - 		[Thumbprint]    : ACFA520F8944C9B926BCDB567215434CD0201FDC
2022/11/16 14:39:01 - 
2022/11/16 14:39:01 - 	Supported Products          : 
2022/11/16 14:39:01 - 		Microsoft.VisualStudio.Community
2022/11/16 14:39:01 - 			Version : [17.0,18.0)
2022/11/16 14:39:01 - 			ProductArchitecture : amd64
2022/11/16 14:39:01 -               : 
2022/11/16 14:39:01 - 		-------------------------------------------------------
2022/11/16 14:39:01 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
2022/11/16 14:39:01 - 		Name         : Visual Studio core editor
2022/11/16 14:39:01 - 		Version      : [17.0,18.0)
2022/11/16 14:39:01 - 
2022/11/16 14:39:01 - 	Extension is signed with a valid signature.
2022/11/16 14:39:01 - 
2022/11/16 14:39:01 - Searching for applicable products...
2022/11/16 14:39:01 - Installed Products Detected - Global Locations
2022/11/16 14:39:01 - Installed products detected - Visual Studio Enterprise 2022
2022/11/16 14:39:01 - VSIXInstaller.NoApplicableSKUsException: This extension cannot be installed on a currently installed product.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by awschristou** [comment] 2022-11-16 16:24
Hi @goblinss , are you working on an ARM based system?

**Comment by goblinss** [comment] 2022-11-16 23:21
Hi @awschristou , Yes.

**Comment by awschristou** [comment] 2022-11-17 16:02
Thank you. This is a duplicate of #291, so I will close it. #302 has been created as the general feature request for an Arm based version of this extension.

**Closed by awschristou** 2022-11-17 16:02 UTC
Labels: duplicate
