### ISSUE TITLE
AWS toolkit breaks VS IntelliSense

### ISSUE THREAD

**Issue by sinand99** [aws/aws-toolkit-visual-studio#387] opened 2024-01-28 00:38 UTC
**Describe the bug**
C# IntelliSense does not show ToolTips when I hover over variables and method calls

**To Reproduce**

    Open a Solution in Visual Studio containing one or more C# source files.
    Open a .cs file in the Editor.
    Hover the mouse over an event, class, interface, method call, or property.

**Expected behavior**
A ToolTip appears, displaying the signature of the method or other item, along with any documentation.

**Development System (please complete the following information):**
- Windows Version: Windows 11
- Visual Studio Version: VS 2022
- AWS Toolkit for Visual Studio Version: Latest

 [Microsoft confirms that this is a AWS extension bug.](https://developercommunity.visualstudio.com/t/C-IntelliSense-does-not-show-ToolTips-w/10537707?sort=newest&viewtype=all)

**Comment by awschristou** [comment] 2024-01-30 01:11
Thanks for reaching out @sinand99 , looking at the linked developer community ticket, it looks like the Refactoring Toolkit is the problem, which is a different extension from the [AWS Toolkit for Visual Studio](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2022):

> I have positively identified that the AWS Toolkit for .NET Refactoring VS 2022 extension (https://marketplace.visualstudio.com/items?itemName=AWSTR.refactoringtoolkit2022) is the culprit.

The AWS Toolkit for .NET Refactoring VS 2022 extension does not have a corresponding GitHub issue, but you can send an email to the team at aws-toolkit-for-net-refactoring-support@amazon.com in order to get help. I will now close this issue, as it doesn't relate to the AWS Toolkit for Visual Studio.

**Closed by awschristou** 2024-01-30 01:11 UTC
Labels: bug

**Comment by sinand99** [comment] 2024-01-30 03:11
> Thanks for reaching out @sinand99 , looking at the linked developer community ticket, it looks like the Refactoring Toolkit is the problem, which is a different extension from the [AWS Toolkit for Visual Studio](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2022):
> 
> > I have positively identified that the AWS Toolkit for .NET Refactoring VS 2022 extension (https://marketplace.visualstudio.com/items?itemName=AWSTR.refactoringtoolkit2022) is the culprit.
> 
> The AWS Toolkit for .NET Refactoring VS 2022 extension does not have a corresponding GitHub issue, but you can send an email to the team at [aws-toolkit-for-net-refactoring-support@amazon.com](mailto:aws-toolkit-for-net-refactoring-support@amazon.com) in order to get help. I will now close this issue, as it doesn't relate to the AWS Toolkit for Visual Studio.

I just gave it as an example, since both extensions share the same bug. Please do not close this, as it is NOT solved yet.

**Comment by awschristou** [comment] 2024-01-30 18:37
Hi @sinand99 , I have the AWS Toolkit for Visual Studio installed, and do not have the refactoring Toolkit installed. 

I have signed in to CodeWhisperer, and I am unable to reproduce the issue. Here you can see I am hovering over a property, and getting intellisense while calling a method.

![image](https://github.com/aws/aws-toolkit-visual-studio/assets/39839589/0166408e-0cee-4d53-88d0-4d530a173928)

You may want to consider disabling and/or uninstalling one or both extensions, restarting Visual Studio, and trying again to see if the issue persists.
