### ISSUE TITLE
"Deploy to AWS CloudFormation" right click context menu option is missing

### ISSUE THREAD

**Issue by fayeg21** [aws/aws-toolkit-visual-studio#284] opened 2022-09-09 11:04 UTC
**Describe the bug**
AWS docs (https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/tkv-cfn-editor-deploy-template.html) say that one shold be able to right click in a template file in the "Solution Explorer" and see an option to "Deploy to AWS CloudFormation".

However this option is not showing up.  See attached screen shot.
![missing_context](https://user-images.githubusercontent.com/113093946/189335138-f80f0949-3742-4c83-87cc-a868401dc379.png)

**To Reproduce**
Steps to reproduce the behavior
example:
1. Start a new CF project
2. Create and save a new template
3. Open the Solution Explorer
4. Right click on template file name 

**Expected behavior**
To see an option to deploy as cloudformation

**Screenshots**
![missing_context](https://user-images.githubusercontent.com/113093946/189335138-f80f0949-3742-4c83-87cc-a868401dc379.png)

**Computer (please complete the following information):**

- Windows Version: Windows 10 Home, 21H2, Build 19044.1889
- Visual Studio Version: Microsoft Visual Studio Community 2022, Version 17.3.3, VisualStudio.17.Release/17.3.3+32825.248
- AWS Toolkit for Visual Studio Version: 1.35.2.0

**Additional context**

**Comment by shruti0085** [comment] 2022-09-09 16:43
Hello @fayeg21, Thank you for reaching out.
The screenshot attached seems to indicate that the project has been opened/loaded in Folder view. The `Deploy To AWS CloudFormation` action appears on the context menu for the template when the solution for the project is loaded/viewed in the Solution Explorer.
Do you see the same behavior when the solution for the project is loaded in the Solution Explorer?

**Comment by fayeg21** [comment] 2022-09-12 09:24
> 

Hi shruti0085,

When I open up the project this is what I see in the "Solution Explorer" in Visual Studio:
![Screenshot vs snip](https://user-images.githubusercontent.com/113093946/189617313-a5239447-5b97-4f82-b8a7-3be1ec1d49b6.png)

When I right click on the sln file this is what I get:

![Screenshot vs snip 2](https://user-images.githubusercontent.com/113093946/189617629-5b4de939-789c-448a-b217-46fdfe56bdac.png)

when I select "Open" I get this:

![Screenshot vs snip 3](https://user-images.githubusercontent.com/113093946/189618011-e9082f87-cc36-4259-b1e7-65bbed552904.png)

Please note the "unloaded" which is covered in this issue: 

https://github.com/aws/aws-toolkit-visual-studio/issues/227

Right clicking on the context here allows me to reload the project which gets me past that particular bug leaving the Solution Exploror looking like this:

![Screenshot 4](https://user-images.githubusercontent.com/113093946/189618566-87d6b76d-fb91-40b4-bd7b-596df47370dd.png)

I've tried all the icons along the top of "Solution Explorer" none of them presents a menu that has "Deploy to CF" as a right click context menu item

Please advise what I'm failing to do.

**Comment by awschristou** [comment] 2022-09-16 17:24
Hi @fayeg21 , when you try to reload the project from the context menu, can you please confirm that the shared screenshot represents what you see on your system? It looks the same as the previous image, so I'm interested to know if Visual Studio is still showing the project as unloaded afterwards.

**Comment by rbbarad** [comment] 2023-07-18 23:51
Closing this issue as a duplicate of https://github.com/aws/aws-toolkit-visual-studio/issues/227, which was fixed in version 1.39.0.0 of the Toolkit. Please open a new issue if this is persisting for you in the latest version of the Toolkit.

**Closed by rbbarad** 2023-07-18 23:51 UTC
Labels: bug
