### ISSUE TITLE
cant deloy 

### ISSUE THREAD

**Issue by proper77** [aws/aws-toolkit-visual-studio#432] opened 2024-06-21 04:02 UTC
![Uploading Screenshot 2024-06-21 064932.png…]()

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Toolkit Logs**

**Development System (please complete the following information):**
- Windows Version:
- Visual Studio Version:
- AWS Toolkit for Visual Studio Version:

**Additional context**

**Comment by awschristou** [comment] 2024-06-21 15:16
Closing as duplicate of #430

**Closed by awschristou** 2024-06-21 15:16 UTC
Labels: bug
