### ISSUE TITLE
failed while publish to aws ECS.. using AWS toolbar

### ISSUE THREAD

**Issue by fpranadi** [aws/aws-toolkit-visual-studio#319] opened 2023-02-12 09:46 UTC
```
#4 [internal] load metadata for mcr.microsoft.com/do
...
Error truncated to the first and last 500 characters
...
ild "wanotif.balisoket.com.csproj" -c Release -o /app/build]: exit code: 1
------
 > [build 7/7] RUN dotnet build "wanotif..csproj" -c Release -o /app/build:
------
executor failed running [/bin/sh -c dotnet build "wanotif.csproj" -c Release -o /app/build]: exit code: 1

Docker builds usually fail due to executing them from a working directory that is incompatible with the Dockerfile.
You can try setting the 'Docker Execution Directory' in the option settings.
wanotif.balisoket.com failed to publish to AWS.
```

**Computer (please complete the following information):**

- Windows Version: windows 10
- Visual Studio Version: 2019
- AWS Toolkit for Visual Studio Version: 2022

**Comment by awschristou** [comment] 2023-02-13 15:42
Hi @fpranadi , it sounds like your project's docker file is not able to build correctly. Please have a look at https://aws.github.io/aws-dotnet-deploy/troubleshooting-guide/docker-issues/ for some troubleshooting tips.

**Comment by shruti0085** [comment] 2023-05-11 22:01
Closing this issue since we haven’t heard back from you in a while. If you are still encountering this problem please open a new issue with detailed steps to reproduce it.

**Closed by shruti0085** 2023-05-11 22:01 UTC
Labels: bug, needs-response, publish
