### ISSUE TITLE
Docker not detected on new Publish to AWS feature

### ISSUE THREAD

**Issue by danielbichuetti** [aws/aws-toolkit-visual-studio#205] opened 2021-12-21 19:25 UTC
**Describe the bug**
When going to publish on the new publish Preview feature option, docker is said as missing. I'm using a Windows 11 machine and running Visual Studio 2022 Preview with Docker 4.3.1. Docker is acessible from path and exposed on TCP port. 

**To Reproduce**
1. Create new Web project on VS2022
2. Right click on project csproj and choose Publish to AWS (Preview Feature)
3. Wait for loading
4. Docker is said missing

**Expected behavior**
Docker should have been detected as it's acessible on terminal and TCP port.

**Computer (please complete the following information):**

- Windows Version: 11
- Visual Studio Version: 2022 17.1.0 Preview 1.1
- AWS Toolkit for Visual Studio Version: 1.23.3

**Additional context**

**Comment by danielbichuetti** [comment] 2021-12-22 10:39
After testing during some time I got to one conclusion and pattern.

It happens that AWS Toolkit (and aws-dotnet deploy) can't identify docker as installed if another context  then default is being used at the right moment. 

Maybe it tool could detect non default context being used and rollback to default or at least warn user of it, and not say docker not installed.

**Comment by awschristou** [comment] 2022-07-06 17:10
Can you check if this problem exists in the latest version of the Toolkit? If so, please share repro steps for placing docker on another context.

**Comment by nyan-cat** [comment] 2022-12-12 11:16
One year has passed, and still no solution! Windows 11, latest VS 2022, latest Docker, latest AWS extension, and the issue is still there! It doesn't see docker installed! Is this Amazon? Really?

**Comment by philasmar** [comment] 2023-01-23 18:27
To be able to understand the issue better, are you able to see if this issue is reproducible in the .NET CLI https://github.com/aws/aws-dotnet-deploy?
Also, from the VS Toolkit, have you ever been able to get docker to work at all? Is this a persistent or transient issue. 
Do you see any errors in the VS Toolkit logs?
This is the code we are running to check docker https://github.com/aws/aws-dotnet-deploy/blob/e8f4ad1dc07cb3c191f4623d72a971dc3b27527a/src/AWS.Deploy.Orchestration/SystemCapabilityEvaluator.cs#L49. Can you check what error you get if you run that from the Command line?

**Comment by Spejik** [comment] 2023-04-07 19:45
> 

I had the same issue, tried running that command, got "ERROR: error during connect: This error may indicate that the docker daemon is not running."
Maybe other people also didn't have docker running?
Anyway just starting Docker desktop seems to fix it. Maybe it would be nice to add a pop-up window like Docker tools for Visual Studio has, reminding people docker isn't running.

**Comment by 96malhar** [comment] 2023-11-29 19:44
Tried reproducing this issue in the following environment:
* OS - Windows 10
* Docker Desktop - v4.0.0 (67817)
* Docker Engine - v20.10.8
* Visual Studio Professional 2022 - v17.8.2
* AWS Toolkit for Visual Studio 2022 - v1.45.0.0

**Scenario 1**: Docker Desktop not running while deploying the [ConsoleAppTask](https://github.com/aws/aws-dotnet-deploy/tree/main/testapps/ConsoleAppTask) to ECS Fargate
![image](https://github.com/aws/aws-toolkit-visual-studio/assets/36622308/606a22a2-e9d9-43a1-b6ab-5cfc89ab90f3)

**Scenario 2**: Docker Desktop running in Windows mode while deploying the [ConsoleAppTask](https://github.com/aws/aws-dotnet-deploy/tree/main/testapps/ConsoleAppTask) to ECS Fargate
![image](https://github.com/aws/aws-toolkit-visual-studio/assets/36622308/d5921f0c-6bab-4d3b-ab6a-c5da632ec9d7)

**Scenario 3:** Docker Desktop running in Linux mode while deploying the [ConsoleAppTask](https://github.com/aws/aws-dotnet-deploy/tree/main/testapps/ConsoleAppTask) to ECS Fargate.
**Result**: The deployment is successful

I have not been able to reproduce the user reported issue on the latest version of the AWS Toolkit for Visual Studio 2022. Requesting the toolkits team (@awschristou @shruti0085 @floralph) to close this issue since it no longer persists and there are no action items on our end.

**Comment by shruti0085** [comment] 2023-12-14 20:17
Closing this as the issue seems no longer applicable(based on the comment above) with the latest versions of the aws-dotnet-deploy tool and the toolkit.
If you have any other updates or specifics you can share, please create a new issue and provide relevant details for us to further investigate it.

**Closed by shruti0085** 2023-12-14 20:17 UTC
Labels: bug, needs-response, publish, no-autoclose
