### ISSUE TITLE
QChat for Visual Studio Professional

### ISSUE THREAD

**Issue by MarcoSchneider-TUI** [aws/aws-toolkit-visual-studio#394] opened 2024-02-13 09:23 UTC
Hi,
I would like to have AWS Q-Chat available in Toolkit for VisualStudio 2022 Professional Version.

Thanks and best regards
Marco

**Comment by awschristou** [comment] 2024-02-13 17:17
Thanks for reaching out @MarcoSchneider-TUI . This is a duplicate of the request in #392 , and will be closed. Please add a +1 reaction to that issue to register your interest in this feature.

![image](https://github.com/aws/aws-toolkit-visual-studio/assets/39839589/7812353e-6f05-4247-9cfe-6c0db51a937f)

**Closed by awschristou** 2024-02-13 17:17 UTC
Labels: feature-request
