### ISSUE TITLE
CreateInstance failed for package [AWSToolkitPackage]

### ISSUE THREAD

**Issue by charles310** [aws/aws-toolkit-visual-studio#140] opened 2021-01-04 13:43 UTC
<description>CreateInstance failed for package [AWSToolkitPackage]Source: &apos;mscorlib&apos; Description: Exception has been thrown by the target of an invocation.&#x000D;&#x000A;System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; System.TypeInitializationException: The type initializer for &apos;Amazon.AWSToolkit.Settings.ToolkitSettings&apos; threw an exception. ---&gt; System.MissingMethodException: Method not found: &apos;Amazon.Runtime.Internal.Settings.IPersistenceManager Amazon.Runtime.Internal.Settings.PersistenceManager.get_Instance()&apos;.&#x000D;&#x000A;   at Amazon.AWSToolkit.Settings.SettingsPersistence..ctor()&#x000D;&#x000A;   at Amazon.AWSToolkit.Settings.ToolkitSettings.Initialize()&#x000D;&#x000A;   at Amazon.AWSToolkit.Settings.ToolkitSettings..cctor()&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage..ctor()&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean&amp; canBeCached, RuntimeMethodHandleInternal&amp; ctor, Boolean&amp; bNeedSecurityCheck)&#x000D;&#x000A;   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Activator.CreateInstance(Type type, Boolean nonPublic)&#x000D;&#x000A;   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)System.TypeInitializationException: The type initializer for &apos;Amazon.AWSToolkit.Settings.ToolkitSettings&apos; threw an exception. ---&gt; System.MissingMethodException: Method not found: &apos;Amazon.Runtime.Internal.Settings.IPersistenceManager Amazon.Runtime.Internal.Settings.PersistenceManager.get_Instance()&apos;.&#x000D;&#x000A;   at Amazon.AWSToolkit.Settings.SettingsPersistence..ctor()&#x000D;&#x000A;   at Amazon.AWSToolkit.Settings.ToolkitSettings.Initialize()&#x000D;&#x000A;   at Amazon.AWSToolkit.Settings.ToolkitSettings..cctor()&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage..ctor()System.MissingMethodException: Method not found: &apos;Amazon.Runtime.Internal.Settings.IPersistenceManager Amazon.Runtime.Internal.Settings.PersistenceManager.get_Instance()&apos;.&#x000D;&#x000A;   at Amazon.AWSToolkit.Settings.SettingsPersistence..ctor()&#x000D;&#x000A;   at Amazon.AWSToolkit.Settings.ToolkitSettings.Initialize()&#x000D;&#x000A;   at Amazon.AWSToolkit.Settings.ToolkitSettings..cctor()</description>

- Windows Version: Windows 10
- Visual Studio Version: VS 2019 Professional
- AWS Toolkit for Visual Studio Version: 1.20
-

**Comment by awschristou** [comment] 2021-01-04 16:26
Closing as a duplicate of #138

**Closed by awschristou** 2021-01-04 16:26 UTC
Labels: bug
