### ISSUE TITLE
Publish to AWS not working - but Legacy publish works fine

### ISSUE THREAD

**Issue by JCMReddie** [aws/aws-toolkit-visual-studio#397] opened 2024-02-22 20:10 UTC
I installed the AWS Toolkit version 1.48.0.0.  

When I try to publish to the AWS Region US East (Ohio) - after 2-3 minutes I get an error "Unable to start a deployment session: A task was canceled."
 
If I switch to the US East (N. Virginia) region - after several minutes I see the "Publish to New Target" and "Publish to Existing Target" options.

**Comment by JCMReddie** [comment] 2024-02-22 20:14
Here is what I think is the appropriate message from the AWSToolkit logs:
2024-02-22 15:09:11,703 [41] ERROR Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Error setting deployment target
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AWS.Deploy.ServerMode.Client.RestAPIClient.<SetDeploymentTargetAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<InvokeSetDeploymentTargetAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<SetDeploymentTargetAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<SetDeploymentTargetAsync>d__182.MoveNext()
2024-02-22 15:09:11,704 [41] ERROR Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl - Error reloading configuration details
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AWS.Deploy.ServerMode.Client.RestAPIClient.<SetDeploymentTargetAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<InvokeSetDeploymentTargetAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<SetDeploymentTargetAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<SetDeploymentTargetAsync>d__182.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl.<ReloadTargetConfigurationsAsync>d__41.MoveNext()
2024-02-22 15:09:22,092 [227] ERROR Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl - Error refreshing publish state
Amazon.AWSToolkit.Publish.SessionException: Unable to start a deployment session:
A task was canceled. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AWS.Deploy.ServerMode.Client.RestAPIClient.<StartDeploymentSessionAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<StartSessionAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<StartDeploymentSessionAsync>d__162.MoveNext()
   --- End of inner exception stack trace ---
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<StartDeploymentSessionAsync>d__162.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<RestartDeploymentSessionAsync>d__160.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl.<RestartDeploymentSessionAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl.<OnTerminalConnectionManagerStateAsync>d__27.MoveNext()

**Comment by ScottDellinger** [comment] 2024-06-13 01:20
@JCMReddie Did you ever get this figured out? One of my dev team are experiencing this issue as well (but on CA-Central-1), but the rest of the team isn't and we're stumped.

**Comment by dtechfish** [comment] 2024-09-16 21:50
Did anyone get this working?  I'm having the same issue. I've reinstalled visual studio, reinstalled the aws toolkit extension, and rebuilt the credentials files.  Nothing seems to work... except the legacy version.  Any suggestions would be helpful.  

Here's my log:

2024-09-16 16:43:18,821 [102] DEBUG Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Starting a deployment session
2024-09-16 16:43:28,223 [94] DEBUG Amazon.AWSToolkit.Telemetry.Internal.TelemetryPublisher - Publishing 15 event(s)
2024-09-16 16:44:58,831 [28] ERROR Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl - Error refreshing publish state
Amazon.AWSToolkit.Publish.SessionException: Unable to start a deployment session:
A task was canceled. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AWS.Deploy.ServerMode.Client.RestAPIClient.<StartDeploymentSessionAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<StartSessionAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<StartDeploymentSessionAsync>d__162.MoveNext()
   --- End of inner exception stack trace ---
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<StartDeploymentSessionAsync>d__162.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<RestartDeploymentSessionAsync>d__160.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl.<RestartDeploymentSessionAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl.<OnTerminalConnectionManagerStateAsync>d__27.MoveNext()

**Comment by nicklmiller** [comment] 2024-11-22 19:19
Anyone find a fix for this? We are getting the exact same error. @JCMReddie @ScottDellinger

**Comment by ScottDellinger** [comment] 2024-11-22 19:53
@nicklmiller Sadly, no. We stopped using Visual Studio for publishing and now use a CI/CD pipeline.

**Comment by awschristou** [comment] 2024-11-27 18:34
I'm going to close this issue as a duplicate of #427, where we are interested in learning more about this problem.

**Closed by awschristou** 2024-11-27 18:34 UTC
