### ISSUE TITLE
Keep User signed in

### ISSUE THREAD

**Issue by marcoschneidertui** [aws/aws-toolkit-visual-studio#395] opened 2024-02-15 07:12 UTC
**Is your feature request related to a problem? Please describe.**
Feature Request: every time a new visual studio project is loaded, or visual studio is reloaded, Sign in to BuilderId must be renewed. This is not very handy and can easily be forgotten

**Describe the solution you'd like**
Last successful sign-in should be kept and automatically be reapplied when a new project is loaded or visual studio is restarted

**Comment by marcoschneidertui** [comment] 2024-02-15 08:22
Further more even after a little inactivity the user must re sign in.
![image](https://github.com/aws/aws-toolkit-visual-studio/assets/30691895/e360bab8-86d3-4beb-8f62-48b3d5125d1e)

At least a setting for the timeout value would be nice to have

**Comment by awschristou** [comment] 2024-02-15 20:01
Hi @marcoschneidertui , can you please share additional details around your configuration:
- what type of credentials are you using: Builder ID, or IAM Identity Center?
- how often are you seeing the expiration prompt: every 5 minutes? Once a day?

**Comment by marcoschneidertui** [comment] 2024-02-20 07:28
Hi @awschristou ,
I use Builder ID provided by my company.
I see that for sure every time I start a new instance of Visual Studio, but also after some inactivity (not really sure if that is 5 mins or more) but I see that multiple times a day.

**Comment by awschristou** [comment] 2024-02-20 18:57
Thank you for the details @marcoschneidertui 

Out of curiosity:
- are you also using the same Builder ID account to clone CodeCatalyst repos?
- are you also using the same Builder ID account (on the same system) with either of the AWS Toolkits for VS Code or JetBrains?

**Comment by marcoschneidertui** [comment] 2024-02-21 07:01
Hi @awschristou,
no we are neither using CodeCatalyst nor do I use other IDE than Visual Studio Professional. I have AWS Toolkit not even installed for VS Code.

**Comment by awschristou** [comment] 2024-03-08 18:58
Hi @marcoschneidertui , we've just released a new version of the Toolkit (1.49.0.0). This version has some updates to how the SSO login flow behave. Can you update your toolkit and try this out for a couple of days, and let us know if you are still seeing frequent sign-in prompts?

**Comment by marcoschneidertui** [comment] 2024-03-12 10:38
Hi @awschristou ,
thanks for letting me know.
I tested this morning with the new release of the toolkit. 

Unfortunately I still experience that issue still, that I need to re-signin after a small inactivity. It was around 10-15 mins inactivty.
I think this should not happen. From my opinion re-signin should only be necessary if I start a new instance of visual studio but until I do not close it, why do I need to re-signin? This is very disturbing and sometimes you not immediately recongnize but start to wonder why you do not get code recommendations.

**Comment by awschristou** [comment] 2024-03-12 17:48
That is definitely a strange behavior. A couple of things we can look into:
- is your system clock reasonably close to the current time?
- what time zone is your system set to?

Knowing this, lets examine one your SSO token. Close down all of your instances of Visual Studio. Go into the `%userprofile%\.aws\sso\cache` folder, and delete all of the files. This will cause you to go through the SSO login flow in your tooling again. (If you wanted, you could just move these files out of the folder for this experiment, and then move them back in to the folder afterwards).

Now, launch the Toolkit, and sign in to CodeWhisperer. Make note of the time you did this. Once you're signed in and getting suggestions, return to the cache folder, and look at the contents of the token files. I'm interested in knowing:
- what time you signed in
- the value of `expiresAt`
- the value of `registrationExpiresAt`

**Comment by marcoschneidertui** [comment] 2024-03-13 09:35
Hi @awschristou ,
I did the requested steps. My computer is setup in CET timezone. Time is correctly setup. As this is an enterprice laptop, such settings are controlled through our AD.

I performed a new signin at 10:25 (probably finished at 10:26). A new file was created in the cache folder with this content:
![image](https://github.com/aws/aws-toolkit-visual-studio/assets/30691895/fc7963e5-1b97-45c8-b7ff-88b0fd4786c5)

**Comment by marcoschneidertui** [comment] 2024-03-13 10:34
It took around 10 mins of inactivity until I had to signin again. Before re-signin, the content of the file in cache folder has not been changed anyhow.

**Comment by marcoschneidertui** [comment] 2024-03-13 13:30
I just had the case, that even when activly working in visual studio, code whisperer asked me to resignin:
![image](https://github.com/aws/aws-toolkit-visual-studio/assets/30691895/2231338e-c6ce-4d37-9712-993875a95b3b)

Is there maybe some option available to enable some debug logging?

**Comment by awschristou** [comment] 2024-03-13 18:41
Thank you for the details. I have tried setting my system to UTC+1 (instead of UTC-8) and debugged the login/refresh flows, to see if there was an errant Local (instead of UTC) datetime comparison somewhere. My debugging session showed the time checks working as expected, and I wasn't able to reproduce your scenario.

Let me think about this some more. If I was to make a special build of the toolkit that contained extra logging, would you be open to the idea of trying it in order to try and narrow down the problem space?

**Comment by marcoschneidertui** [comment] 2024-03-14 06:53
Hi, 
sure, happy to support.

**Comment by awschristou** [comment] 2024-03-14 18:24
Thank you @marcoschneidertui 

I have made a new build of the toolkit. I based it on the 1.49.0.0 release, and added more logging statements to the CodeWhisperer token handling/refreshing/expiration areas. I have posted the build at https://github.com/aws/aws-toolkit-visual-studio/releases/tag/Issue-395 for you to download and install.

Once you've installed it, sign out of CodeWhisperer and re-sign in. Assuming you get the expired notification in the same small timeframe, once you are shown the expiration notice, obtain the Toolkit logs for that instance-session of Visual Studio by going to the **Extensions** > **AWS Toolkit** > **View Toolkit Logs** menu. Please attach that log to this issue. I'll be interested to see how the Toolkit interpreted the token expiration times.

**Comment by marcoschneidertui** [comment] 2024-03-15 06:34
Hi @awschristou ,
I installed the version. Unfortunately, today I do not have development work to do and next week I am off.
I will provide my feedback and logs in the week starting 25th March.

**Comment by awschristou** [comment] 2024-03-15 17:04
Sounds great, thank you for the update.

**Comment by awschristou** [comment] 2024-03-26 00:02
Thank you for sharing these logs @marcoschneidertui. From the logs, I could see that the initial sign-in was working as expected, and an attempt is made to refresh the token about 55 minutes later, as expected. However in your case, the refresh was not successful.

I was able to reproduce this scenario when I set up an IAM IdC that was based on a region other than `us-east-1`. I tried using `eu-central-1` to more closely [match what you appear to be using](https://github.com/aws/aws-toolkit-visual-studio/issues/395#issuecomment-1993949863).

It looks like the Toolkit was missing this region assignment when performing the token refresh checks. I've made a change that should fix this scenario, and have produced a new test build. I have updated the build posted at https://github.com/aws/aws-toolkit-visual-studio/releases/tag/Issue-395, and would be interested in hearing if this works for you. I'd like to know if you sign in and use/leave Visual Studio running for at least an hour, if you still get an expired notification or not.

In your Toolkit logs, after the "SSO Expiration check starting" message, instead of seeing "SSO Token could not be refreshed", we should see "SSO Token was refreshed" if this fix works.

**Comment by marcoschneidertui** [comment] 2024-03-26 09:29
Hi @awschristou ,
I tested that new version. Unfortunately the error happened again, but I took much longer until it appeared.
Further more, after starting a new instance, the sign in was automatically happening, which was not the case with previous versions, so that is at least a good improvement.

I attach the latest log. It contains several token renewals which worked fine, but one of it failed unfortunately.

[log_2024-03-26_07-48-13_1584.txt](https://github.com/aws/aws-toolkit-visual-studio/files/14755948/log_2024-03-26_07-48-13_1584.txt)

**Comment by awschristou** [comment] 2024-03-26 15:48
Hi @marcoschneidertui , thank you for trying the new build and sharing an update. It looks like things are working as expected, and your token was refreshed a couple of times.

Can you please check with your IAM Identity Center administrator what the session duration is configured to be? This sample image shows where that is located. This would be the upper limit before your sign-in would expire, which would require a new sign-in. Currently this could be configured anywhere between 15 minutes and 90 days. Once we know whether or not your Toolkit behavior is following this configuration, we'll know if there is additional investigation required.
![image](https://github.com/aws/aws-toolkit-visual-studio/assets/39839589/5e1bfae2-6fa6-499f-bb19-5adc975232f3)

In the meantime, I will get the fixes we've tested prepared for a future Toolkit release.

**Comment by marcoschneidertui** [comment] 2024-03-27 06:14
Hi @awschristou ,
I talked with our Organization Maintainer. He told me, that our SSO settings are currently configured with 14days session duration.

**Comment by marcoschneidertui** [comment] 2024-03-27 14:33
Hi @awschristou ,
just to let you know, I worked nearly the whole day now in Visual Studio without any re-signin attempt. So it seems the issue is fixed and that one yesterday was just a "hick-up"

**Comment by awschristou** [comment] 2024-03-27 15:27
Thanks for the update @marcoschneidertui - this is good news. It is possible that the token that expired was one that your IDE started using up to 14 days ago. Even when the Toolkit with a bug failed to refresh the token, it may have remained, and the Test versions of the Toolkit continued to use it and successfully refresh with it.

I will leave this issue open until the test fix is available in a Toolkit release. Then I will close this ticket and delete the test build from this repo's releases.

**Comment by floralph** [comment] 2024-04-01 20:55
We've just released version 1.50.0.0 of the toolkit which contains a fix to refresh SSO tokens when using a region outside of the US.

**Closed by floralph** 2024-04-01 20:55 UTC
Labels: bug, auth, pending-release
